[[redirects]]
  from = "/2023/users/*/__og_image__/og.png"
  to = "/2023/users/:splat/__og_image__/og.png"
  status = 200

[[redirects]]
  from = "/2023/users/*"
  to = "/2023/200.html"
  status = 200

[[redirects]]
  from = "/2023/*"
  to = "/2023/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/2023/:splat"
  status = 301

[functions.server]
  external_node_modules = ["chrome-aws-lambda"]
