import { Sponsor } from '~/types/app'

const all: Sponsor[] = [
  {
    id: 'cloudsign',
    name: 'クラウドサイン（弁護士ドットコム株式会社）',
    nameKey: 'sponsors.cloudsign',
    image: 'sponsors/cloudsign.png',
    categories: ['platinum', 'session-room-naming-rights'],
    url: 'https://www.cloudsign.jp/',
  },
  {
    id: 'unique-vision',
    name: 'ユニークビジョン株式会社',
    nameKey: 'sponsors.unique_vision',
    image: 'sponsors/unique-vision.png',
    categories: ['platinum'],
    url: 'https://www.uniquevision.co.jp/',
  },
  {
    id: 'link-and-motivation-group',
    name: '株式会社リンクアンドモチベーション',
    nameKey: 'sponsors.link_and_motivation_group',
    image: 'sponsors/link-and-motivation-group.png',
    categories: ['platinum'],
    url: 'https://www.lmi.ne.jp/',
  },
  {
    id: 'yappli',
    name: '株式会社ヤプリ',
    nameKey: 'sponsors.yappli',
    image: 'sponsors/yappli.png',
    categories: ['gold'],
    url: 'https://yappli.co.jp/',
  },
  {
    id: 'future-architect',
    name: 'フューチャーアーキテクト株式会社',
    nameKey: 'sponsors.future_architect',
    image: 'sponsors/future-architect.png',
    categories: ['gold'],
    url: 'https://www.future.co.jp/architect/',
  },
  {
    id: 'jetbrains',
    name: 'JetBrains s.r.o.',
    nameKey: 'jetbrains',
    image: 'sponsors/jetbrains.png',
    categories: ['gold'],
    url: 'https://jb.gg/vuefes2023-webstorm',
  },
  {
    id: 'medpeer',
    name: 'メドピア株式会社',
    nameKey: 'sponsors.medpeer',
    image: 'sponsors/medpeer.png',
    categories: ['gold', 'session-room-naming-rights', 'special-lunch'],
    url: 'https://medpeer.co.jp/',
  },
  {
    id: 'hacomono',
    name: '株式会社hacomono',
    nameKey: 'sponsors.hacomono',
    image: 'sponsors/hacomono.png',
    categories: ['gold', 'special-lunch'],
    url: 'https://recruit.hacomono.jp/',
  },
  {
    id: 'plaid',
    name: '株式会社プレイド',
    nameKey: 'sponsors.plaid',
    image: 'sponsors/plaid.svg',
    categories: ['gold'],
    url: 'https://plaid.co.jp/',
  },
  {
    id: 'base',
    name: 'BASE株式会社',
    nameKey: 'sponsors.base',
    image: 'sponsors/base.png',
    categories: ['silver'],
    url: 'https://thebase.com',
  },
  {
    id: 'cybozu',
    name: 'サイボウズ株式会社',
    nameKey: 'sponsors.cybozu',
    image: 'sponsors/cybozu.png',
    categories: ['silver'],
    url: 'https://tech.cybozu.io/',
  },
  {
    id: 'mntsq',
    name: 'MNTSQ株式会社',
    nameKey: 'sponsors.mntsq',
    image: 'sponsors/mntsq.png',
    categories: ['silver', 'special-lunch'],
    url: 'https://www.mntsq.co.jp/',
  },
  {
    id: 'mierune',
    name: '株式会社MIERUNE',
    nameKey: 'sponsors.mierune',
    image: 'sponsors/mierune.svg',
    categories: ['silver'],
    url: 'https://www.mierune.co.jp',
  },
  {
    id: 'visasq',
    name: '株式会社ビザスク',
    nameKey: 'sponsors.visasq',
    image: 'sponsors/visasq.svg',
    categories: ['silver'],
    url: 'https://service.visasq.com/',
  },
  {
    id: 'stores',
    name: 'STORES株式会社',
    nameKey: 'sponsors.stores',
    image: 'sponsors/stores.png',
    categories: ['silver', 'special-lunch'],
    url: 'https://jobs.st.inc/engineer',
  },
  {
    id: 'line-yahoo-communications',
    name: 'LINEヤフーコミュニケーションズ株式会社',
    nameKey: 'sponsors.line_yahoo_communications',
    image: 'sponsors/line-yahoo-communications.png',
    categories: ['silver'],
    url: 'https://linefukuoka.co.jp/ja/career/engineer',
  },
  {
    id: 'raksul',
    name: 'ラクスル株式会社',
    nameKey: 'sponsors.raksul',
    image: 'sponsors/raksul.jpg',
    categories: ['silver'],
    url: 'https://corp.raksul.com/',
  },
  {
    id: 'lapras',
    name: 'LAPRAS株式会社',
    nameKey: 'sponsors.lapras',
    image: 'sponsors/lapras.png',
    categories: ['silver'],
    url: 'https://lapras.com/person',
  },
  {
    id: 'giftee',
    name: '株式会社ギフティ',
    nameKey: 'sponsors.giftee',
    image: 'sponsors/giftee.png',
    categories: ['silver', 'refreshment'],
    url: 'https://giftee.co.jp/',
  },
  {
    id: 'tanomu',
    name: '株式会社タノム',
    nameKey: 'sponsors.tanomu',
    image: 'sponsors/tanomu.png',
    categories: ['bronze', 'name-card'],
    url: 'https://lp.tano.mu',
  },
  {
    id: 'studist',
    name: '株式会社スタディスト',
    nameKey: 'sponsors.studist',
    image: 'sponsors/studist.png',
    categories: ['bronze'],
    url: 'https://studist.jp/',
  },
  {
    id: 'coco',
    name: '株式会社coco',
    nameKey: 'sponsors.coco',
    image: 'sponsors/coco.png',
    categories: ['bronze'],
    url: 'https://thecoco.jp/',
  },
  {
    id: 'tential',
    name: '株式会社TENTIAL',
    nameKey: 'sponsors.tential',
    image: 'sponsors/tential.svg',
    categories: ['bronze'],
    url: 'https://corp.tential.jp/',
  },
  {
    id: 'mercari',
    name: '株式会社メルカリ',
    nameKey: 'sponsors.mercari',
    image: 'sponsors/mercari.svg',
    categories: ['bronze'],
    url: 'https://jp.merpay.com',
  },
  {
    id: 'm3',
    name: 'エムスリー株式会社',
    nameKey: 'sponsors.m3',
    image: 'sponsors/m3.svg',
    categories: ['session-room-naming-rights'],
    url: 'https://jobs.m3.com/engineer/',
  },
  {
    id: 'coconala',
    name: '株式会社ココナラ',
    nameKey: 'sponsors.coconala',
    image: 'sponsors/coconala.png',
    categories: ['lunch'],
    url: 'https://coconala.co.jp/',
  },
  {
    id: 'gmo-internet-group',
    name: 'GMOインターネットグループ株式会社',
    nameKey: 'sponsors.gmo_internet_group',
    image: 'sponsors/gmo-internet-group.svg',
    categories: ['after-party'],
    url: 'https://gmo.jp',
  },
  {
    id: 'crowdworks',
    name: '株式会社クラウドワークス',
    nameKey: 'sponsors.crowdworks',
    image: 'sponsors/crowdworks.svg',
    categories: ['simultaneous-interpretation'],
    url: 'https://crowdworks.co.jp/',
  },
  {
    id: 'newt',
    name: 'Newt株式会社',
    nameKey: 'sponsors.newt',
    image: 'sponsors/newt.png',
    categories: ['media'],
    url: 'https://www.newt.so/',
  },
  {
    id: 'gihyojp',
    name: '株式会社技術評論社',
    nameKey: 'sponsors.gihyojp',
    image: 'sponsors/gihyojp.svg',
    categories: ['media'],
    url: 'https://gihyo.jp',
  },
  {
    id: 'yuzuriha',
    name: '株式会社YUZURIHA',
    nameKey: 'sponsors.yuzuriha',
    image: 'sponsors/yuzuriha.png',
    categories: ['bronze'],
    url: 'https://yzrh.jp',
  },
  {
    id: 'attelu',
    name: '株式会社アッテル',
    nameKey: 'sponsors.attelu',
    image: 'sponsors/attelu.svg',
    categories: ['bronze'],
    url: 'https://attelu.jp',
  },
  {
    id: 'algorithms',
    name: '株式会社アルゴリズム',
    nameKey: 'sponsors.algorithms',
    image: 'sponsors/algorithms.png',
    categories: ['bronze'],
    url: 'https://algorithms.co.jp',
  },
  {
    id: 'interfirm',
    name: 'KATIX（株式会社インターファーム）',
    nameKey: 'sponsors.interfirm',
    image: 'sponsors/interfirm.png',
    categories: ['bronze'],
    url: 'https://www.interfirm.jp',
  },
  {
    id: 'tabian',
    name: 'タビアン株式会社',
    nameKey: 'sponsors.tabian',
    image: 'sponsors/tabian.png',
    categories: ['handson'],
    url: 'https://tabian.co.jp',
  },
  {
    id: 'hennge',
    name: 'HENNGE株式会社',
    nameKey: 'sponsors.hennge',
    image: 'sponsors/hennge.png',
    categories: ['bronze', 'refreshment'],
    url: 'https://hennge.com',
  },
  {
    id: 'tam',
    name: '株式会社TAM',
    nameKey: 'sponsors.tam',
    image: 'sponsors/tam.png',
    categories: ['refreshment'],
    url: 'https://www.tam-tam.co.jp',
  },
]

const platinumSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('platinum'))

const goldSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('gold'))

const silverSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('silver'))

const bronzeSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('bronze'))

const namingRightSponsors: Sponsor[] = all.filter((s: Sponsor) =>
  s.categories.includes('session-room-naming-rights'),
)

const specialLunchSponsors: Sponsor[] = all.filter((s: Sponsor) =>
  s.categories.includes('special-lunch'),
)

const lunchSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('lunch'))

const afterPartySponsors: Sponsor[] = all.filter((s: Sponsor) =>
  s.categories.includes('after-party'),
)

const namecardSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('name-card'))

const refreshmentSponsors: Sponsor[] = all.filter((s: Sponsor) =>
  s.categories.includes('refreshment'),
)

const interpretationSponsors: Sponsor[] = all.filter((s: Sponsor) =>
  s.categories.includes('simultaneous-interpretation'),
)

const handsonSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('handson'))

const mediaSponsors: Sponsor[] = all.filter((s: Sponsor) => s.categories.includes('media'))

const individual: string[] = [
  '鈴木 尚栄',
  'jiyuujin',
  'Yuhei FUJITA',
  '今枝 弘貴',
  'オガワシンヤ',
  '田中弘治',
  'Yasunori Kirimoto',
  '向後宗一郎',
  'chan_kaku',
  'Re:Vue',
  'CODE HOUSE',
  '江崎伸英',
  'Vagif Aghayev',
  'タダ タケヒロ',
  'Hiroki Osame',
  'Masayuki Ota',
  'レオン　クリス',
  'R.Okuyama',
  'みなみ@hecateball',
  'arihh',
  'あんど@ampersand_xyz',
  'hakocat85',
  'Jabelic',
  'yug1224',
  '進 正彦',
  '榎本睦大',
  'yamanoku',
  'Shinji Hagiwara',
  'okame',
  '白石祐大',
  'INOUE Takuya',
  '__d',
  '#7',
  'Anton Pushkarev',
  'Anastasiia Pushkareva',
  'モリタリュウイチロウ',
  'nishikiori',
  'みっちー',
  'うめのこ',
  'kzhrk',
  'kobeshanks',
  'Zeals',
]

export {
  platinumSponsors,
  goldSponsors,
  silverSponsors,
  bronzeSponsors,
  namingRightSponsors,
  specialLunchSponsors,
  lunchSponsors,
  afterPartySponsors,
  namecardSponsors,
  interpretationSponsors,
  handsonSponsors,
  refreshmentSponsors,
  mediaSponsors,
  individual,
  all,
}
