import { Team, Volunteer } from '~/types/app'
import { twitterDomainUrl } from '~/utils/constants'

export const teams: Team[] = [
  {
    image: '2023/teams/kazupon.png',
    name: 'kazupon',
    snsLink: `${twitterDomainUrl}kazu_pon`,
  },
  {
    image: '2023/teams/448jp.png',
    name: '448jp',
    snsLink: `${twitterDomainUrl}448jp`,
  },
  {
    image: '2023/teams/aster.jpeg',
    name: 'aster-mnch',
    snsLink: '',
  },
  {
    image: '2023/teams/becolomochi.png',
    name: 'becolomochi',
    snsLink: `${twitterDomainUrl}becolomochi`,
  },
  {
    image: '2023/teams/fulu.jpg',
    name: 'fulu',
    snsLink: `${twitterDomainUrl}firirice`,
  },
  {
    image: '2023/teams/happylifetaka.png',
    name: 'happylifetaka',
    snsLink: `${twitterDomainUrl}happylifetaka`,
  },
  {
    image: '2023/teams/jayes.png',
    name: 'jay-es',
    snsLink: `${twitterDomainUrl}shindy_JP`,
  },
  {
    image: '2023/teams/jiyuujin.png',
    name: 'jiyuujin',
    snsLink: `${twitterDomainUrl}jiyuujinlab`,
  },
  {
    image: '2023/teams/kame.png',
    name: 'kame',
    snsLink: `${twitterDomainUrl}dir20634`,
  },
  {
    image: '2023/teams/keigo.jpg',
    name: 'keigo',
    snsLink: `${twitterDomainUrl}Kspace_trk`,
  },
  {
    image: '2023/teams/kiaking.jpg',
    name: 'kiaking',
    snsLink: `${twitterDomainUrl}KiaKing85`,
  },
  {
    image: '2023/teams/kokoakuma.jpeg',
    name: 'kokoakuma',
    snsLink: `${twitterDomainUrl}kokoakuma_dev`,
  },
  {
    image: '2023/teams/maashi.jpg',
    name: 'まぁし',
    snsLink: `${twitterDomainUrl}chocodogmagic`,
  },
  {
    image: '2023/teams/matzryo.jpeg',
    name: 'matzryo',
    snsLink: `${twitterDomainUrl}matzryo`,
  },
  {
    image: '2023/teams/miyake.jpg',
    name: 'miyake',
    snsLink: `${twitterDomainUrl}kazuyukimiyake`,
  },
  {
    image: '2023/teams/moabear.png',
    name: 'moabear',
    snsLink: `${twitterDomainUrl}moa_bear_`,
  },
  {
    image: '2023/teams/momolili.jpg',
    name: 'momolili',
    snsLink: `${twitterDomainUrl}momolili_CS5`,
  },
  {
    image: '2023/teams/nal.jpg',
    name: 'nal',
    snsLink: `${twitterDomainUrl}nal_pan`,
  },
  {
    image: '2023/teams/naramochi.png',
    name: 'naramochi',
    snsLink: `${twitterDomainUrl}_naramochi`,
  },
  {
    image: '2023/teams/nokki.jpeg',
    name: 'nokki',
    snsLink: `${twitterDomainUrl}nokki_y`,
  },
  {
    image: '2023/teams/nozomu.png',
    name: 'nozomu.ikuta',
    snsLink: `${twitterDomainUrl}NozomuIkuta`,
  },
  {
    image: '2023/teams/oreo.png',
    name: 'oreo',
    snsLink: `${twitterDomainUrl}oreo2991`,
  },
  {
    image: '2023/teams/robjam.JPG',
    name: 'robjam',
    snsLink: `${twitterDomainUrl}robjamdev`,
  },
  {
    image: '2023/teams/ryo_gk.jpeg',
    name: 'ryo_gk',
    snsLink: `${twitterDomainUrl}ryo_gk55`,
  },
  {
    image: '2023/teams/ryoaccount.jpg',
    name: 'ryoAccount',
    snsLink: `${twitterDomainUrl}RYO_nami`,
  },
  {
    image: '2023/teams/ryuhei.jpg',
    name: 'ryuhei373',
    snsLink: `${twitterDomainUrl}373_3`,
  },
  {
    image: '2023/teams/sanadi.jpg',
    name: 'Sanadi',
    snsLink: `${twitterDomainUrl}favorita_biz`,
  },
  {
    image: '2023/teams/shinya.jpg',
    name: 'shinya ogawa',
    snsLink: `${twitterDomainUrl}DesignSupplyWeb`,
  },
  {
    image: '2023/teams/shiori.jpg',
    name: 'shiori',
    snsLink: `${twitterDomainUrl}dummy11022`,
  },
  {
    image: '2023/teams/shiyuu.png',
    name: 'shiyuu',
    snsLink: `${twitterDomainUrl}shiyuu33`,
  },
  {
    image: '2023/teams/takuan.png',
    name: 'takuan',
    snsLink: `${twitterDomainUrl}takuan517`,
  },
  {
    image: '2023/teams/taniiiiim.png',
    name: 'taniiiiim',
    snsLink: `${twitterDomainUrl}taniiiiim`,
  },
  {
    image: '2023/teams/tokuda.png',
    name: 'tokuda109',
    snsLink: `${twitterDomainUrl}tokuda109`,
  },
  {
    image: '2023/teams/torish.png',
    name: 'torish14',
    snsLink: `${twitterDomainUrl}torish14_str`,
  },
  {
    image: '2023/teams/toshick.png',
    name: 'toshick',
    snsLink: `${twitterDomainUrl}toshick`,
  },
  {
    image: '2023/teams/tutti.jpg',
    name: 'tutti',
    snsLink: `${twitterDomainUrl}tutti2612`,
  },
  {
    image: '2023/teams/watasan.jpg',
    name: 'watasan',
    snsLink: `${twitterDomainUrl}hishiwata7`,
  },
  {
    image: '2023/teams/watsuyo.jpg',
    name: 'watsuyo',
    snsLink: `${twitterDomainUrl}watsuyo_2`,
  },
  {
    image: '2023/teams/yamageji.png',
    name: 'yamageji',
    snsLink: `${twitterDomainUrl}yamageji`,
  },
  {
    image: '2023/teams/yuhei.jpg',
    name: 'Yuhei FUJITA',
    snsLink: `${twitterDomainUrl}Yuhei_FUJITA`,
  },
  {
    image: '2023/teams/yurufuwa.jpg',
    name: 'yurufuwaFE',
    snsLink: `${twitterDomainUrl}yurufuwaFE`,
  },
  {
    image: '2023/teams/yuuki.jpg',
    name: 'Yuuki Ishibashi',
    snsLink: `${twitterDomainUrl}Bassy3600`,
  },
  {
    image: '2023/teams/4mdy.png',
    name: '4mdy',
    snsLink: `${twitterDomainUrl}__4mdy`,
  },
  {
    image: '2023/teams/nakamoto.png',
    name: '仲本勇斗',
    snsLink: '',
  },
  {
    image: '2023/teams/kumin.png',
    name: '平間久美子',
    snsLink: `${twitterDomainUrl}kumin`,
  },
  {
    image: '2023/teams/hirano.png',
    name: '平野 雅一',
    snsLink: `${twitterDomainUrl}Hirano_Tech`,
  },
]

export const volunteers: Volunteer[] = [
  { name: 'Shuntaro Miwa' },
  { name: 'csy19' },
  { name: 'ひな' },
  { name: 'nabekura' },
  { name: 'hiroko_ino' },
  { name: 'よしぴー' },
  { name: 'horiiiiii032929' },
  { name: 'Naoyuki Yamada' },
  { name: 'げんじ' },
  { name: 'maru' },
  { name: '日隈壮一郎' },
  { name: 'Kota Fujishiro' },
  { name: '福田繁之' },
  { name: 'とよへい' },
  { name: 'isamusuzuki' },
  { name: 'Yuto NAGAI' },
  { name: 'Arisa' },
  { name: 'Marianna' },
  { name: 'でろ' },
  { name: 'kaeru_note' },
  { name: 'Keisuke Sawa' },
  { name: 'Midori Tanaka' },
  { name: 'Tsuge' },
  { name: 'Risa Okutani' },
  { name: 'すぎしお' },
  { name: 'Shun Nakano' },
  { name: 'Shunsuke Nakamura' },
  { name: 'Charles Montgomery' },
  { name: 'ubugeeei' },
  { name: 'Kiyoshi Yamashita' },
  { name: 'Hatsuki Saito' },
  { name: 'Yosuke Ythe Sato' },
  { name: 'tatsugooon' },
  { name: '内藤 航介' },
  { name: 'ryo-endo' },
  { name: 'takeaship' },
  { name: 'ponyoxa' },
  { name: 'みーた' },
  { name: 'くろきり' },
  { name: 'ruka' },
  { name: 'Takatoshi Tenko' },
]
