import { Team } from '~/types/app'
export const teams: Team[] = [
  {
    image: 'teams/kazupon.png',
    name: 'kazupon',
    snsId: 'kazu_pon',
    snsLink: 'https://twitter.com/kazu_pon',
  },
  {
    image: 'teams/448jp.png',
    name: '448jp',
    snsId: '448jp',
    snsLink: 'https://twitter.com/448jp',
  },
  {
    image: 'teams/aster.jpeg',
    name: 'aster-mnch',
    snsId: 'aster-mnch',
    snsLink: '',
  },
  {
    image: 'teams/becolomochi.png',
    name: 'becolomochi',
    snsId: 'becolomochi',
    snsLink: 'https://twitter.com/becolomochi',
  },
  {
    image: 'teams/fulu.jpg',
    name: 'fulu',
    snsId: 'firirice',
    snsLink: 'https://twitter.com/firirice',
  },
  {
    image: 'teams/happylifetaka.png',
    name: 'happylifetaka',
    snsId: 'happylifetaka',
    snsLink: 'https://twitter.com/happylifetaka',
  },
  {
    image: 'teams/jayes.png',
    name: 'jay-es',
    snsId: 'shindy_JP',
    snsLink: 'https://twitter.com/shindy_JP',
  },
  {
    image: 'teams/jiyuujin.png',
    name: 'jiyuujin',
    snsId: 'jiyuujin',
    snsLink: 'https://twitter.com/jiyuujinlab',
  },
  {
    image: 'teams/kame.png',
    name: 'kame',
    snsId: 'dir20634',
    snsLink: 'https://twitter.com/dir20634',
  },
  {
    image: 'teams/keigo.jpg',
    name: 'keigo',
    snsId: 'Kspace_trk',
    snsLink: 'https://twitter.com/Kspace_trk',
  },
  {
    image: 'teams/kiaking.jpg',
    name: 'kiaking',
    snsId: 'kiaking',
    snsLink: 'https://twitter.com/KiaKing85',
  },
  {
    image: 'teams/kokoakuma.jpeg',
    name: 'kokoakuma',
    snsId: 'kokoakuma_dev',
    snsLink: 'https://twitter.com/kokoakuma_dev',
  },
  {
    image: 'teams/maashi.jpg',
    name: 'まぁし',
    snsId: 'chocodogmagic',
    snsLink: 'https://twitter.com/chocodogmagic',
  },
  {
    image: 'teams/matzryo.jpeg',
    name: 'matzryo',
    snsId: 'matzryo',
    snsLink: 'https://twitter.com/matzryo',
  },
  {
    image: 'teams/miyake.jpg',
    name: 'miyake',
    snsId: 'kazuyukimiyake',
    snsLink: 'https://twitter.com/kazuyukimiyake',
  },
  {
    image: 'teams/moabear.png',
    name: 'moabear',
    snsId: 'moa_bear_',
    snsLink: 'https://twitter.com/moa_bear_',
  },
  {
    image: 'teams/momolili.jpg',
    name: 'momolili',
    snsId: 'momolili_CS5',
    snsLink: 'https://twitter.com/momolili_CS5',
  },
  {
    image: 'teams/nal.jpg',
    name: 'nal',
    snsId: 'nal_pan',
    snsLink: 'https://twitter.com/nal_pan',
  },
  {
    image: 'teams/naramochi.png',
    name: 'naramochi',
    snsId: '_naramochi',
    snsLink: 'https://twitter.com/_naramochi',
  },
  {
    image: 'teams/nokki.jpeg',
    name: 'nokki',
    snsId: 'nokki_y',
    snsLink: 'https://twitter.com/nokki_y',
  },
  {
    image: 'teams/nozomu.png',
    name: 'nozomu.ikuta',
    snsId: 'NozomuIkuta',
    snsLink: 'https://twitter.com/NozomuIkuta',
  },
  {
    image: 'teams/oreo.png',
    name: 'oreo',
    snsId: 'oreo',
    snsLink: 'https://twitter.com/oreo2991',
  },
  {
    image: 'teams/robjam.JPG',
    name: 'robjam',
    snsId: 'robjamdev',
    snsLink: 'https://twitter.com/robjamdev',
  },
  {
    image: 'teams/ryo_gk.jpeg',
    name: 'ryo_gk',
    snsId: 'ryo_gk55',
    snsLink: 'https://twitter.com/ryo_gk55',
  },
  {
    image: 'teams/ryoaccount.jpg',
    name: 'ryoAccount',
    snsId: 'ryoAccount',
    snsLink: 'https://twitter.com/RYO_nami',
  },
  {
    image: 'teams/ryuhei.jpg',
    name: 'ryuhei373',
    snsId: '373_3',
    snsLink: 'https://twitter.com/373_3',
  },
  {
    image: 'teams/sanadi.jpg',
    name: 'Sanadi',
    snsId: 'favorita_biz',
    snsLink: 'https://twitter.com/favorita_biz',
  },
  {
    image: 'teams/shinya.jpg',
    name: 'shinya ogawa',
    snsId: 'DesignSupplyWeb',
    snsLink: 'https://twitter.com/DesignSupplyWeb',
  },
  {
    image: 'teams/shiori.jpg',
    name: 'shiori',
    snsId: 'dummy11022',
    snsLink: 'https://twitter.com/dummy11022',
  },
  {
    image: 'teams/shiyuu.png',
    name: 'shiyuu',
    snsId: 'shiyuu33',
    snsLink: 'https://twitter.com/shiyuu33',
  },
  {
    image: 'teams/takuan.png',
    name: 'takuan',
    snsId: 'takuan517',
    snsLink: 'https://twitter.com/takuan517',
  },
  {
    image: 'teams/tokuda.png',
    name: 'tokuda109',
    snsId: 'tokuda109',
    snsLink: 'https://twitter.com/tokuda109',
  },
  {
    image: 'teams/torish.png',
    name: 'torish14',
    snsId: 'torish14',
    snsLink: 'https://twitter.com/torish14_str',
  },
  {
    image: 'teams/toshick.png',
    name: 'toshick',
    snsId: 'toshick',
    snsLink: 'https://twitter.com/toshick',
  },
  {
    image: 'teams/tutti.jpg',
    name: 'tutti',
    snsId: 'tutti2612',
    snsLink: 'https://twitter.com/tutti2612',
  },
  {
    image: 'teams/watasan.jpg',
    name: 'watasan',
    snsId: 'hishiwata7',
    snsLink: 'https://twitter.com/hishiwata7',
  },
  {
    image: 'teams/watsuyo.jpg',
    name: 'watsuyo',
    snsId: 'watsuyo',
    snsLink: 'https://twitter.com/watsuyo_2',
  },
  {
    image: 'teams/yuhei.jpg',
    name: 'Yuhei FUJITA',
    snsId: 'Yuhei_FUJITA',
    snsLink: 'https://twitter.com/Yuhei_FUJITA',
  },
  {
    image: 'teams/yurufuwa.jpg',
    name: 'yurufuwaFE',
    snsId: 'yurufuwaFE',
    snsLink: 'https://twitter.com/yurufuwaFE',
  },
  {
    image: 'teams/yuuki.jpg',
    name: 'Yuuki Ishibashi',
    snsId: 'Bassy3600',
    snsLink: 'https://twitter.com/Bassy3600',
  },
  {
    image: 'teams/nakamoto.png',
    name: '仲本勇斗',
    snsId: 'n_tacorice',
    snsLink: '',
  },
  {
    image: 'teams/kumin.png',
    name: '平間久美子',
    snsId: 'kumin',
    snsLink: 'https://twitter.com/kumin',
  },
  {
    image: 'teams/hirano.png',
    name: '平野 雅一',
    snsId: 'Hirano_Tech',
    snsLink: 'https://twitter.com/Hirano_Tech',
  },
]
